# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cCKPVCyQ1nQEN3awJXwLDjSLTw2morMw
"""

import json
import os
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Prompt, IntPrompt
from rich import print as rprint

FILENAME = "tasks.json"
console = Console()

def load_tasks():
    if not os.path.exists(FILENAME):
        return []
    try:
        with open(FILENAME, "r") as file:
            return json.load(file)
    except (json.JSONDecodeError, IOError):
        return []

def save_tasks(tasks):
    try:
        with open(FILENAME, "w") as file:
            json.dump(tasks, file, indent=4)
    except IOError as e:
        rprint(f"[bold red]Error saving tasks:[/bold red] {e}")

def list_tasks(tasks):
    console.clear()
    if not tasks:
        rprint(Panel("[yellow]Your task list is empty. Add something to get started![/yellow]", title="Status"))
        return

    table = Table(title="Student Task Manager", show_header=True, header_style="bold cyan")
    table.add_column("#", style="dim", width=4)
    table.add_column("Task Description", min_width=20)
    table.add_column("Status", justify="center")

    for idx, task in enumerate(tasks, 1):
        status = "[green]✅ Done[/green]" if task["done"] else "[red]⏳ Pending[/red]"
        style = "strike dim" if task["done"] else ""
        table.add_row(str(idx), task['description'], status, style=style)

    console.print(table)

def add_task(tasks):
    description = Prompt.ask("\n[bold blue]What needs to be done?[/bold blue]")
    if description:
        tasks.append({"description": description, "done": False})
        save_tasks(tasks)
        rprint("[bold green]✨ Task added successfully![/bold green]")

def mark_done(tasks):
    list_tasks(tasks)
    if not tasks: return

    choice = IntPrompt.ask("\n[bold magenta]Enter the task number to complete[/bold magenta]")
    if 1 <= choice <= len(tasks):
        tasks[choice - 1]["done"] = True
        save_tasks(tasks)
        rprint("[bold green]Check! Task marked as completed.[/bold green]")
    else:
        rprint("[bold red]Invalid task number.[/bold red]")

def main():
    tasks = load_tasks()

    while True:
        list_tasks(tasks)
        rprint("\n[bold]1.[/bold] View [bold]2.[/bold] Add [bold]3.[/bold] Complete [bold]4.[/bold] Exit")
        choice = Prompt.ask("Choose an action", choices=["1", "2", "3", "4"], default="1")

        if choice == '1':
            list_tasks(tasks)
            input("\nPress Enter to return to menu...")
        elif choice == '2':
            add_task(tasks)
        elif choice == '3':
            mark_done(tasks)
        elif choice == '4':
            rprint("[italic cyan]Goodbye! Go crush those tasks.[/italic cyan]")
            break

if __name__ == "__main__":
    main()